# embed_spirv.cmake
# Reads a binary file (a .spv blob) and emits a C++ header that contains the
# bytes as a 4-byte-aligned constexpr unsigned char array plus its length.
#
# Invoked as:
#   cmake -DINPUT=<file.spv> -DOUTPUT=<file.h> -DVARNAME=<symbol> -P embed_spirv.cmake
#
# SPIR-V is a stream of 32-bit words; we store it as bytes but force 4-byte
# alignment so it can be reinterpret_cast<const uint32_t*> safely at load time.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VARNAME)
    message(FATAL_ERROR "embed_spirv.cmake requires -DINPUT -DOUTPUT -DVARNAME")
endif()

file(READ "${INPUT}" hex HEX)
string(REGEX MATCHALL "[0-9a-f][0-9a-f]" bytes "${hex}")
list(LENGTH bytes byte_count)

# Build the comma-separated initializer in chunks to keep CMake string ops fast.
set(body "")
set(line "")
set(col 0)
foreach(b IN LISTS bytes)
    string(APPEND line "0x${b},")
    math(EXPR col "${col}+1")
    if(col GREATER_EQUAL 20)
        string(APPEND body "    ${line}\n")
        set(line "")
        set(col 0)
    endif()
endforeach()
if(NOT line STREQUAL "")
    string(APPEND body "    ${line}\n")
endif()

set(content "// Auto-generated by embed_spirv.cmake. Do not edit.\n")
string(APPEND content "#pragma once\n")
string(APPEND content "#include <cstddef>\n")
string(APPEND content "alignas(4) static const unsigned char ${VARNAME}[] = {\n")
string(APPEND content "${body}")
string(APPEND content "};\n")
string(APPEND content "static const size_t ${VARNAME}_len = ${byte_count};\n")

file(WRITE "${OUTPUT}" "${content}")
